feat: allow pass full qualified callback url to passport and make sur…
eggjs/egg-passport pull request #11
Opened 2019-06-05 07:31 UTC by Jeff-Tian

…e the authentication generate the correct redirect_uri.

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change
在对接 github oauth 时发现 redirect_uri 总是不匹配的问题，最终找到的原因是，我的站点部署到了 https 下，而该插件在生成 authentication 时，redirect_uri 总是 http 的。

于是尝试在 mount 时，把 https://example.com/passport/github/callback 这样的完整 url 传进去，但是仍然会出问题。

所以改造了 passport 的 mount 方法，使其接受完整的 url，这样，最终生成的 redirect_uri 就是对的了（https）。

附上了测试代码验证通过。

2019-06-05 08:00 UTC, Jeff-Tian commented
第一次提交的单元测试失败了，应该是 .travis 的 secure 过期了，需要重新生成，暂时用EGG_PASSPORT_WEIBO_CLIENT_ID=xxx EGG_PASSPORT_WEIBO_CLIENT_SECRET=yyy EGG_PASSPORT_TWITTER_CONSUMER_KEY=xxx EGG_PASSPORT_TWITTER_CONSUMER_SECRET=yyy 绕过……

![image](https://user-images.githubusercontent.com/3367820/58938739-1fd7c280-87a8-11e9-9cb5-ebeae3f826f6.png)

2019-06-05 08:25 UTC, Jeff-Tian commented
## 更多解释：

源码：https://github.com/Jeff-Tian/alpha
部署：https://uniheart.herokuapp.com/

参考了 eggjs 的 passport 示例代码，发现部署在 heroku 上后，总是 redirect_uri 错误。

原来是 redirect_uri 总是 http:// 开头，最后定位到 egg-passport.mount() 方法，默认 callbackURL 是一个相对路径，最终在 passport 库里，这个相对路径会被添加一个 http:// 开头的协议（可能是 heroku 使用了 http 直接）。

而 passport 库是允许传入完成 url 作为 callbackURL 的，不过，目前 egg-passport.mount() 方法只接受相对路径的 options，所以改了一下这个方法，解决了，可以访问 https://uniheart.herokuapp.com/ 看效果。

2019-06-06 02:41 UTC, thonatos requested changes

2019-06-06 02:41 UTC, thonatos commented on lib/passport.js
>      options.loginURL = options.loginURL || `/passport/${strategy}`;
正常来说，参数处理应该放在前面吧

```js
    options.loginURL = url.parse(options.loginURL || `/passport/${strategy}`).pathname;
    options.callbackURL = url.parse(options.callbackURL || `/passport/${strategy}/callback`).pathname;
    const auth = this.authenticate(strategy, options);
    this.app.get(options.loginURL, auth);
    this.app.get(options.callbackURL, auth);
    this.app.get(options.loginURL, auth);
    this.app.get(options.callbackURL, auth);
```

2019-06-06 02:41 UTC, thonatos commented on package.json
> +  "version": "2.0.2",
版本发布的时候会改, PR 里面不需要的

2019-06-06 02:41 UTC, thonatos commented on package.json
> +    "cov": "EGG_PASSPORT_WEIBO_CLIENT_ID=xxx EGG_PASSPORT_WEIBO_CLIENT_SECRET=yyy EGG_PASSPORT_TWITTER_CONSUMER_KEY=xxx EGG_PASSPORT_TWITTER_CONSUMER_SECRET=yyy egg-bin cov",
CI 已经配过环境变量了，这里也补需要

2019-06-06 03:49 UTC, Jeff-Tian commented on package.json
> +    "cov": "EGG_PASSPORT_WEIBO_CLIENT_ID=xxx EGG_PASSPORT_WEIBO_CLIENT_SECRET=yyy EGG_PASSPORT_TWITTER_CONSUMER_KEY=xxx EGG_PASSPORT_TWITTER_CONSUMER_SECRET=yyy egg-bin cov",
@thonatos 好的，我把它去掉。

2019-06-06 03:50 UTC, Jeff-Tian commented on package.json
> +  "version": "2.0.2",
行，我回滚第二个提交

2019-06-06 04:04 UTC, Jeff-Tian commented on lib/passport.js
>      options.loginURL = options.loginURL || `/passport/${strategy}`;
@thonatos 对于传入完整 url 的场景，`auth = this.authenticate(strategy, options)` 仍然需要完整的路径，只是 `this.app.get()` 无论哪种场景，都是需要相对路径，所以把 `url.parse().pathname` 放在了调用 `this.app.get()` 处。（而且这样能避免副作用，不然的话，把传入参数给改掉了。）

2019-06-06 04:10 UTC, Jeff-Tian commented on package.json
> +    "cov": "EGG_PASSPORT_WEIBO_CLIENT_ID=xxx EGG_PASSPORT_WEIBO_CLIENT_SECRET=yyy EGG_PASSPORT_TWITTER_CONSUMER_KEY=xxx EGG_PASSPORT_TWITTER_CONSUMER_SECRET=yyy egg-bin cov",
已去掉，各位大佬们更新下 CI 配置哈

2019-06-13 07:32 UTC, thonatos commented on package.json
> +    "cov": "EGG_PASSPORT_WEIBO_CLIENT_ID=xxx EGG_PASSPORT_WEIBO_CLIENT_SECRET=yyy EGG_PASSPORT_TWITTER_CONSUMER_KEY=xxx EGG_PASSPORT_TWITTER_CONSUMER_SECRET=yyy egg-bin cov",
求老板 @fengmk2 更新一下 `Token`.

2019-06-14 05:35 UTC, merged

2019-06-14 05:36 UTC, thonatos commented
Token 问题是没权限执行，先合并了